# MySQL (default setup).

production:
  adapter: mysql2
  database: redmine
  host: localhost
  username: root
  password:
  encoding: utf8
 
#production:
#  adapter: sqlite3
#  database: /var/lib/redmine/redmine.db
 
